#!/bin/bash -e
###############################################################################
#
# Copyright 2022 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################

cd ${0%*/*}

if [ ! -e Dockerfile ]; then
	echo "ERROR: Dockerfile is missing."
	exit 1
fi

if ! (which wget > /dev/null 2>&1); then
	echo "wget is required to build BFB"
	exit 1
fi

if ! (which docker > /dev/null 2>&1); then
	echo "docker is required to build BFB"
	exit 1
fi

DISTRO="ubuntu"
DISTRO_VERSION="22.04"
DISTRO_BASE_URL="https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-arm64-root.tar.xz"
DOCA_VERSION="2.5.0"
BSP_VERSION="4.5.0-12993"
MLNX_OFED_VERSION="23.10-1.2.0.0"
IMAGE_TYPE=${IMAGE_TYPE:-"prod"}
CUSTOM_VERSION=${CUSTOM_VERSION:-""}

WDIR=/tmp/${DISTRO}${DISTRO_VERSION}.$$
BASE_URL=${BASE_URL:-"https://linux.mellanox.com/public/repo"}

DEPS_DIR=$(readlink -f ../../uc22-deps)

mkdir -p $WDIR
mkdir -p $DEPS_DIR
echo "current pwd: $(pwd), deps dir is: ${DEPS_DIR}"
if [ -f "$DEPS_DIR/mlxbf-scripts_arm64.deb" ]; then
	echo "Using local mlxbf-scripts_arm64.deb"
	cp $DEPS_DIR/mlxbf-scripts_arm64.deb $WDIR/mlxbf-scripts_arm64.deb
else
	echo "Downloading mlxbf-scripts..."
	wget -q -P $WDIR -r --no-verbose --no-directories -l1 --no-parent -A 'mlxbf-scripts_3.6_arm64.deb' ${BASE_URL}/doca/${DOCA_VERSION}/${DISTRO}${DISTRO_VERSION}/aarch64/
	mv $WDIR/mlxbf-scripts_3.6_arm64.deb $WDIR/mlxbf-scripts_arm64.deb
	cp $WDIR/mlxbf-scripts_arm64.deb $DEPS_DIR/mlxbf-scripts_arm64.deb
fi
if [ -f "$DEPS_DIR/mlxbf-bootctl_arm64.deb" ]; then
	echo "Using local mlxbf-bootctl_arm64.deb"
	cp $DEPS_DIR/mlxbf-bootctl_arm64.deb $WDIR/mlxbf-bootctl_arm64.deb
else
	echo "Downloading mlxbf-bootctl..."
	wget -q -P $WDIR -r --no-verbose --no-directories -l1 --no-parent -A 'mlxbf-bootctl_2.1_arm64.deb' ${BASE_URL}/doca/${DOCA_VERSION}/${DISTRO}${DISTRO_VERSION}/aarch64/
	mv $WDIR/mlxbf-bootctl_2.1_arm64.deb $WDIR/mlxbf-bootctl_arm64.deb
	cp $WDIR/mlxbf-bootctl_arm64.deb $DEPS_DIR/mlxbf-bootctl_arm64.deb
fi
if [ -f "$DEPS_DIR/mlxbf-bootimages.deb" ]; then
	echo "Using local mlxbf-bootimages_arm64.deb"
	cp $DEPS_DIR/mlxbf-bootimages.deb $WDIR/mlxbf-bootimages.deb
else
	echo "Downloading mlxbf-bootimages..."
	wget -q -P $WDIR -r --no-verbose --no-directories -l1 --no-parent -A 'mlxbf-bootimages*arm64.deb' ${BASE_URL}/bluefield/${BSP_VERSION}/bootimages/${IMAGE_TYPE}/
	mv $WDIR/mlxbf-bootimages*arm64.deb $WDIR/mlxbf-bootimages.deb
	cp $WDIR/mlxbf-bootimages.deb $DEPS_DIR/mlxbf-bootimages.deb
fi
if [ -f "$DEPS_DIR/jammy-server-cloudimg-arm64-root.tar.xz" ]; then
	echo "Using local jammy-server-cloudimg-arm64-root.tar.xz"
	cp $DEPS_DIR/jammy-server-cloudimg-arm64-root.tar.xz $WDIR/
else
	echo "Downloading $DISTRO base image..."
	wget -q -P $WDIR -r --no-verbose --no-directories -l1 --no-parent $DISTRO_BASE_URL
	cp $WDIR/jammy-server-cloudimg-arm64-root.tar.xz $DEPS_DIR/jammy-server-cloudimg-arm64-root.tar.xz
fi

kernel_debs_count=$(find "$DEPS_DIR/kernel-debs" -name "*.deb" 2> /dev/null | wc -l)
if [ "$kernel_debs_count" -eq 5 ]; then
	echo "Using local kernel-debs"
	cp -r $DEPS_DIR/kernel-debs $WDIR/
else
	echo "Downloading kernel-debs..."
	mkdir -p $WDIR/kernel-debs
	kernel_debs=(
		linux-bluefield-headers-5.15.0-1035_5.15.0-1035.37_all.deb
		linux-headers-5.15.0-1035-bluefield_5.15.0-1035.37_arm64.deb
		linux-image-5.15.0-1035-bluefield_5.15.0-1035.37_arm64.deb
		linux-modules-5.15.0-1035-bluefield_5.15.0-1035.37_arm64.deb
		linux-modules-extra-5.15.0-1035-bluefield_5.15.0-1035.37_arm64.deb
	)
	mellanox_deb_url=https://linux.mellanox.com/public/repo/doca/2.6.0/ubuntu22.04/dpu-arm64/
	for deb in ${kernel_debs[@]}; do
		wget -q -P $WDIR -r --no-verbose --no-directories -l1 --no-parent -A $deb $mellanox_deb_url
		mv $WDIR/$deb $WDIR/kernel-debs/
	done
	cp -r $WDIR/kernel-debs $DEPS_DIR/
fi

git rev-parse --short HEAD > $WDIR/COMMIT_HASH

cp	Dockerfile \
	build_ubuntu_bfb \
	create_bfb \
	install.sh \
	../../common/tools/qemu-aarch64-static \
	$WDIR

echo "Retrieve UC22 image ubuntu-core-22-arm64.img.xz from bfb_build parent folder"
cp ../../../ubuntu-core-22-arm64.img.xz $WDIR/

cd $WDIR

docker_image=bfb_runtime_${DISTRO,,}${DISTRO_VERSION,,}

docker rm -f BlueField_OS_${DISTRO}_${DISTRO_VERSION} 2> /dev/null

sed -i -e "s/@IMAGE_TYPE@/$IMAGE_TYPE/g;s/@CUSTOM_VERSION@/$CUSTOM_VERSION/g" \
    -e "s,@BASE_URL@,$BASE_URL,g" \
    -e "s/@DOCA_VERSION@/$DOCA_VERSION/g" Dockerfile

DOCKER_BUILDKIT=0 docker build -t ${docker_image} \
	--build-arg BASE_URL=$BASE_URL \
	--build-arg DOCA_VERSION=$DOCA_VERSION \
	--build-arg BSP_VERSION=$BSP_VERSION \
	--build-arg DISTRO=$DISTRO \
	--build-arg DISTRO_VERSION=$DISTRO_VERSION \
	-f Dockerfile .

docker run -t --rm --privileged -e container=docker \
	-v $PWD:/workspace \
	--name BlueField_OS_${DISTRO}_${DISTRO_VERSION} \
	--mount type=bind,source=/dev,target=/dev \
	--mount type=bind,source=/sys,target=/sys \
	--mount type=bind,source=/proc,target=/proc \
	${docker_image}

path_built_image=$(readlink -f *.bfb)
fixed_path_built_image="/tmp/my_bfb.bfb"
# use copy so we can direct the stream properly
cp ${path_built_image} ${fixed_path_built_image}

echo "${path_built_image} links to ${fixed_path_built_image}"
echo "Default user/password is: ubuntu/ubuntu"
