#!/bin/bash -e
###############################################################################
#
# Copyright 2022 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################

cd ${0%*/*}

if [ ! -e Dockerfile ]; then
	echo "ERROR: Dockerfile is missing."
	exit 1
fi

if ! (which wget > /dev/null 2>&1); then
	echo "wget is required to build BFB"
	exit 1
fi

if ! (which docker > /dev/null 2>&1); then
	echo "docker is required to build BFB"
	exit 1
fi

DISTRO="ubuntu"
DISTRO_VERSION="22.04"
DISTRO_BASE_URL="https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-arm64-root.tar.xz"
DOCA_VERSION="2.5.0"
BSP_VERSION="4.5.0-12993"
MLNX_OFED_VERSION="23.10-1.2.0.0"
IMAGE_TYPE=${IMAGE_TYPE:-"prod"}
CUSTOM_VERSION=${CUSTOM_VERSION:-""}

WDIR=/tmp/${DISTRO}${DISTRO_VERSION}.$$
BASE_URL=${BASE_URL:-"https://linux.mellanox.com/public/repo"}

mkdir -p $WDIR
echo "Downloading mlxbf-scripts..."
if [ -f "../../../mlxbf-scripts_arm64.deb" ]; then
	echo "Using existing mlxbf-scripts_arm64.deb"
	cp ../../../mlxbf-scripts_arm64.deb $WDIR/mlxbf-scripts_arm64.deb
else
	wget -q -P $WDIR -r --no-verbose --no-directories -l1 --no-parent -A 'mlxbf-scripts_3.6_arm64.deb' ${BASE_URL}/doca/${DOCA_VERSION}/${DISTRO}${DISTRO_VERSION}/aarch64/
	mv $WDIR/mlxbf-scripts_3.6_arm64.deb $WDIR/mlxbf-scripts_arm64.deb
fi
echo "Downloading mlxbf-bootctl..."
if [ -f "../../../mlxbf-bootctl_arm64.deb" ]; then
	echo "Using existing mlxbf-bootctl_arm64.deb"
	cp ../../../mlxbf-bootctl_arm64.deb $WDIR/mlxbf-bootctl_arm64.deb
else
	wget -q -P $WDIR -r --no-verbose --no-directories -l1 --no-parent -A 'mlxbf-bootctl_2.1_arm64.deb' ${BASE_URL}/doca/${DOCA_VERSION}/${DISTRO}${DISTRO_VERSION}/aarch64/
	mv $WDIR/mlxbf-bootctl_2.1_arm64.deb $WDIR/mlxbf-bootctl_arm64.deb
fi
echo "Downloading mlxbf-bootimages..."
if [ -f "../../../mlxbf-bootimages.deb" ]; then
	echo "Using existing mlxbf-bootimages_arm64.deb"
	cp ../../../mlxbf-bootimages.deb $WDIR/mlxbf-bootimages.deb
else
	wget -q -P $WDIR -r --no-verbose --no-directories -l1 --no-parent -A 'mlxbf-bootimages*arm64.deb' ${BASE_URL}/bluefield/${BSP_VERSION}/bootimages/${IMAGE_TYPE}/
	mv $WDIR/mlxbf-bootimages*arm64.deb $WDIR/mlxbf-bootimages.deb
fi
echo "Downloading $DISTRO base image..."
if [ -f "../../../jammy-server-cloudimg-arm64-root.tar.xz" ]; then
	echo "Using existing jammy-server-cloudimg-arm64-root.tar.xz"
	cp ../../../jammy-server-cloudimg-arm64-root.tar.xz $WDIR/
else
	wget -q --show-progress --no-check-certificate $DISTRO_BASE_URL
fi

if [ -d "../../../kernel-debs" ]; then
	echo "Using existing kernel-debs"
	cp -r ../../../kernel-debs $WDIR/
fi

git rev-parse --short HEAD > $WDIR/COMMIT_HASH

cp	Dockerfile \
	build_ubuntu_bfb \
	create_bfb \
	install.sh \
	../../common/tools/qemu-aarch64-static \
	$WDIR

cp ../../../ubuntu-core-22-arm64.img.xz $WDIR/

echo "debugging: how big is the core image?"
ls -alh ../../../ubuntu-core-22-arm64*

cd $WDIR

docker_image=bfb_runtime_${DISTRO,,}${DISTRO_VERSION,,}

docker rm -f BlueField_OS_${DISTRO}_${DISTRO_VERSION} 2> /dev/null

sed -i -e "s/@IMAGE_TYPE@/$IMAGE_TYPE/g;s/@CUSTOM_VERSION@/$CUSTOM_VERSION/g" \
    -e "s,@BASE_URL@,$BASE_URL,g" \
    -e "s/@DOCA_VERSION@/$DOCA_VERSION/g" Dockerfile

DOCKER_BUILDKIT=0 docker build -t ${docker_image} \
	--build-arg BASE_URL=$BASE_URL \
	--build-arg DOCA_VERSION=$DOCA_VERSION \
	--build-arg BSP_VERSION=$BSP_VERSION \
	--build-arg DISTRO=$DISTRO \
	--build-arg DISTRO_VERSION=$DISTRO_VERSION \
	-f Dockerfile .

docker run -t --rm --privileged -e container=docker \
	-v $PWD:/workspace \
	--name BlueField_OS_${DISTRO}_${DISTRO_VERSION} \
	--mount type=bind,source=/dev,target=/dev \
	--mount type=bind,source=/sys,target=/sys \
	--mount type=bind,source=/proc,target=/proc \
	${docker_image}

path_built_image=$(readlink -f *.bfb)
fixed_path_built_image="/tmp/my_bfb.bfb"
# use copy so we can direct the stream properly
cp ${path_built_image} ${fixed_path_built_image}

echo "${path_built_image} links to ${fixed_path_built_image}"
echo "Default user/password is: ubuntu/ubuntu"
